---
  - name: Print out Group dictionaries
    hosts: localhost
    gather_facts: false
    vars_files:
      - defaults/main.yml


    tasks:

      - name: Print out all_users_list dictionary 
        loop: "{{ lookup('ansible.builtin.dict', all_users_list) }}"
        ansible.builtin.debug:
          msg: "Employee ID {{ item.key }} belongs to {{ item.value.name }}"

      - name: Print out all_users_email_list dictionary 
        loop: "{{ lookup('ansible.builtin.dict', all_users_email_list) }}"
        ansible.builtin.debug:
          msg: "Employee ID {{ item.key }} belongs to {{ item.value.name }}"

      - name: Compare the dictionaries for sameness
        when: all_users_list ==  all_users_email_list
        ansible.builtin.debug:
          msg: "The dictionaries are identical"

      - name: Compare the dictionaries for difference
        when: all_users_list !=  all_users_email_list
        ansible.builtin.debug:
          msg: "The dictionaries are different"

      - name: test the length of the symmetric difference
        when: diff_keys|length != 0
        ansible.builtin.debug:
          msg: "The difference in the keys: {{ diff_keys }}"

      # - name: Print shit out
      #   when: diff_keys|length == 0
      #   loop: "{{ all_users_list.keys()|sort }}"
      #   ansible.builtin.debug:
      #     msg: "{{ item }} is {{ (all_users_list[item] == all_users_email_list[item])|ternary('OK', 'KO') }}"

      - name: High light the differences between the dictionaries
        when: 
          - diff_keys|length == 0
          - all_users_list[item] != all_users_email_list[item]
        loop: "{{ all_users_list.keys()|sort }}"
        ansible.builtin.set_fact:
          diff_vals: "{{ diff_vals | default({}) | combine ({all_users_list.item}) }}"

      - name: Print out the differences
        ansible.builtin.debug:
          var: diff_vals
